### ISSUE TITLE
Rewrite Migration Logging Inconsistency [TMS 222177]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#158]
When an older copy of the rewritten config is migrated to a newer version, it works as expected.
That is, except loggingLevel, which reverts to INFO regardless of what its existing value was.

# Environment
**Plugin Version**: `ALPHA-1.0.0.4` (Migrating simulated 1.0.0.2 config, Test Environment unit `2-Spigot-Offline-MigOld-Modern-SQL`)
**Server Version**: `3491-Spigot-b081915-95d233d` (MC: 1.18.2) Implementing API Version `1.18.2-R0.1-SNAPSHOT`

# Description.
## Input
See [here](https://github.com/Pheotis/Stargate-Test-Environment/blob/main/2-Spigot-Offline-MigOld-Modern-SQL/plugins/Stargate/config.yml)
```yaml
# Possible Values:
#   |=> SEVERE (Not recommended).
#   |   - 𝐇𝐢𝐝𝐞 𝐞𝐯𝐞𝐫𝐲𝐭𝐡𝐢𝐧𝐠. 𝑂𝑛𝑙𝑦 𝑝𝑟𝑖𝑛𝑡 𝑡𝑜 𝑐𝑜𝑛𝑠𝑜𝑙𝑒 𝑖𝑓 𝑝𝑙𝑢𝑔𝑖𝑛 𝑓𝑎𝑡𝑎𝑙𝑙𝑦 𝑐𝑟𝑎𝑠ℎ𝑒𝑠
#   |=> WARNING (Recommended for large and well-tested production implementations).
#   |   - 𝐇𝐢𝐝𝐞 𝐧𝐨𝐫𝐦𝐚𝐥 𝐛𝐞𝐡𝐚𝐯𝐢𝐨𝐮𝐫. 𝑂𝑛𝑙𝑦 𝑝𝑟𝑖𝑛𝑡 𝑝𝑜𝑡𝑒𝑛𝑡𝑖𝑎𝑙 𝑖𝑠𝑠𝑢𝑒𝑠.
#   |=> INFO (Recommended for most production implementations).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐧𝐨𝐫𝐦𝐚𝐥 𝐛𝐞𝐡𝐚𝐯𝐢𝐨𝐮𝐫. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑝𝑜𝑟𝑡𝑎𝑙 𝑒𝑣𝑒𝑛𝑡𝑠 (𝑢𝑠𝑎𝑔𝑒, 𝑐𝑟𝑒𝑎𝑡𝑖𝑜𝑛, 𝑑𝑒𝑠𝑡𝑟𝑢𝑐𝑡𝑖𝑜𝑛, 𝑒𝑡𝑐.)
#   |=> CONFIG (Useful for configuring preproduction instances).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐩𝐞𝐫𝐦𝐢𝐬𝐬𝐢𝐨𝐧 𝐜𝐡𝐞𝐜𝐤𝐬. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑐ℎ𝑒𝑐𝑘𝑠 𝑚𝑎𝑑𝑒 𝑡𝑜 𝑑𝑒𝑡𝑒𝑟𝑚𝑖𝑛𝑒 𝑖𝑓 𝑝𝑙𝑎𝑦𝑒𝑟𝑠 𝑐𝑎𝑛 𝑝𝑒𝑟𝑓𝑜𝑟𝑚 𝑎𝑛 𝑎𝑐𝑡𝑖𝑜𝑛.
#   |=> FINE (Recommended for basic troubleshooting).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐥𝐢𝐦𝐢𝐭𝐞𝐝 𝐝𝐞𝐛𝐮𝐠 𝐢𝐧𝐟𝐨. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑔𝑒𝑛𝑒𝑟𝑎𝑙 𝑝𝑙𝑢𝑔𝑖𝑛 𝑒𝑣𝑒𝑛𝑡𝑠 (𝑙𝑜𝑎𝑑𝑖𝑛𝑔, 𝑑𝑖𝑠𝑎𝑏𝑙𝑖𝑛𝑔, 𝑐𝑜𝑛𝑛𝑒𝑐𝑡𝑖𝑜𝑛𝑠, 𝑒𝑡𝑐.).
#   |=> FINER (Recommended for some addon developers).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐦𝐨𝐬𝐭 𝐝𝐞𝐛𝐮𝐠 𝐢𝐧𝐟𝐨. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑚𝑒𝑠𝑠𝑎𝑔𝑒𝑠 𝑑𝑒𝑡𝑎𝑖𝑙𝑖𝑛𝑔 𝑡ℎ𝑒 𝑝𝑙𝑢𝑔𝑖𝑛'𝑠 𝑙𝑜𝑔𝑖𝑐 𝑎𝑛𝑑 𝑏𝑒ℎ𝑎𝑣𝑖𝑜𝑢𝑟.
#   |=> FINEST (Only used by StarGate's core development team).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐞𝐯𝐞𝐫𝐲𝐭𝐡𝐢𝐧𝐠. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑙𝑖𝑡𝑒𝑟𝑎𝑙𝑙𝑦 𝑒𝑣𝑒𝑟𝑦𝑡ℎ𝑖𝑛𝑔, 𝑖𝑛𝑐𝑙𝑢𝑑𝑖𝑛𝑔 𝑛𝑢𝑚𝑒𝑟𝑜𝑢𝑠 𝑠𝑡𝑎𝑐𝑘 𝑡𝑟𝑎𝑐𝑒𝑠.
loggingLevel: FINE
```
# Migrated Output:
```yaml
# Possible Values:
#   |=> SEVERE (Not recommended).
#   |   - 𝐇𝐢𝐝𝐞 𝐞𝐯𝐞𝐫𝐲𝐭𝐡𝐢𝐧𝐠. 𝑂𝑛𝑙𝑦 𝑝𝑟𝑖𝑛𝑡 𝑡𝑜 𝑐𝑜𝑛𝑠𝑜𝑙𝑒 𝑖𝑓 𝑝𝑙𝑢𝑔𝑖𝑛 𝑓𝑎𝑡𝑎𝑙𝑙𝑦 𝑐𝑟𝑎𝑠ℎ𝑒𝑠
#   |=> WARNING (Recommended for large and well-tested production implementations).
#   |   - 𝐇𝐢𝐝𝐞 𝐧𝐨𝐫𝐦𝐚𝐥 𝐛𝐞𝐡𝐚𝐯𝐢𝐨𝐮𝐫. 𝑂𝑛𝑙𝑦 𝑝𝑟𝑖𝑛𝑡 𝑝𝑜𝑡𝑒𝑛𝑡𝑖𝑎𝑙 𝑖𝑠𝑠𝑢𝑒𝑠.
#   |=> INFO (Recommended for most production implementations).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐧𝐨𝐫𝐦𝐚𝐥 𝐛𝐞𝐡𝐚𝐯𝐢𝐨𝐮𝐫. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑝𝑜𝑟𝑡𝑎𝑙 𝑒𝑣𝑒𝑛𝑡𝑠 (𝑢𝑠𝑎𝑔𝑒, 𝑐𝑟𝑒𝑎𝑡𝑖𝑜𝑛, 𝑑𝑒𝑠𝑡𝑟𝑢𝑐𝑡𝑖𝑜𝑛, 𝑒𝑡𝑐.)
#   |=> CONFIG (Useful for configuring preproduction instances).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐩𝐞𝐫𝐦𝐢𝐬𝐬𝐢𝐨𝐧 𝐜𝐡𝐞𝐜𝐤𝐬. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑐ℎ𝑒𝑐𝑘𝑠 𝑚𝑎𝑑𝑒 𝑡𝑜 𝑑𝑒𝑡𝑒𝑟𝑚𝑖𝑛𝑒 𝑖𝑓 𝑝𝑙𝑎𝑦𝑒𝑟𝑠 𝑐𝑎𝑛 𝑝𝑒𝑟𝑓𝑜𝑟𝑚 𝑎𝑛 𝑎𝑐𝑡𝑖𝑜𝑛.
#   |=> FINE (Recommended for basic troubleshooting).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐥𝐢𝐦𝐢𝐭𝐞𝐝 𝐝𝐞𝐛𝐮𝐠 𝐢𝐧𝐟𝐨. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑔𝑒𝑛𝑒𝑟𝑎𝑙 𝑝𝑙𝑢𝑔𝑖𝑛 𝑒𝑣𝑒𝑛𝑡𝑠 (𝑙𝑜𝑎𝑑𝑖𝑛𝑔, 𝑑𝑖𝑠𝑎𝑏𝑙𝑖𝑛𝑔, 𝑐𝑜𝑛𝑛𝑒𝑐𝑡𝑖𝑜𝑛𝑠, 𝑒𝑡𝑐.).
#   |=> FINER (Recommended for some addon developers).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐦𝐨𝐬𝐭 𝐝𝐞𝐛𝐮𝐠 𝐢𝐧𝐟𝐨. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑚𝑒𝑠𝑠𝑎𝑔𝑒𝑠 𝑑𝑒𝑡𝑎𝑖𝑙𝑖𝑛𝑔 𝑡ℎ𝑒 𝑝𝑙𝑢𝑔𝑖𝑛'𝑠 𝑙𝑜𝑔𝑖𝑐 𝑎𝑛𝑑 𝑏𝑒ℎ𝑎𝑣𝑖𝑜𝑢𝑟.
#   |=> FINEST (Only used by StarGate's core development team).
#   |   - 𝐏𝐫𝐢𝐧𝐭 𝐞𝐯𝐞𝐫𝐲𝐭𝐡𝐢𝐧𝐠. 𝑃𝑟𝑖𝑛𝑡𝑠 𝑙𝑖𝑡𝑒𝑟𝑎𝑙𝑙𝑦 𝑒𝑣𝑒𝑟𝑦𝑡ℎ𝑖𝑛𝑔, 𝑖𝑛𝑐𝑙𝑢𝑑𝑖𝑛𝑔 𝑛𝑢𝑚𝑒𝑟𝑜𝑢𝑠 𝑠𝑡𝑎𝑐𝑘 𝑡𝑟𝑎𝑐𝑒𝑠.
loggingLevel: INFO
```

**Comment by Pheotis** [comment]
[TMS 222181]
In all cases, the migrator applies an incorrect description to useRemoteDatabase,
![image](https://user-images.githubusercontent.com/49039536/170843916-a83e00bc-fb8c-40c9-bb9a-44acc2ce0e7b.png)

**Comment by EpicKnarvik97** [comment]
The migrator v.1.0.0.0. Is only used for legacy to 1.x.x, so it assumes loggingLevel is not yet an available value. For migrations from 1.0.0.0 to 1.0.0.1, a new Migrator object should be created, which is aware of all 1.0.0.0 configuration values.
The v1.0.0.0 migrator shouldn't run if a migration from legacy to 1.0.0.0 has already been run.

**Comment by EpicKnarvik97** [comment]
usingBungee is also given the wrong description.

![Skjermbilde](https://user-images.githubusercontent.com/3597346/172057388-a0eccc48-012d-4609-bef9-2cda76fb34ef.PNG)

Comparing a migrated config with the default config, there are actually a lot of inconsistencies. General Preferences is replaced with Aesthetic tweaks. The language description is missing.

Default:
```


# +----------------------------------------------------------------------------------------------+ #
# |                                      General Preferences                                     | #
# +----------------------------------------------------------------------------------------------+ #

# What language will stargate use when communicating with your users?
# Supported values: [en,de,nl,no,nn,sv,zh,cs,fr,tr]
#
# If SG isn't yet available in your language, please consider becoming a translator:
# https://crowdin.com/project/stargate-bukkit
language: en

bungee:
  # Are you connected to a bungee-compatible proxy?
  # Set this to true if you intend on building gates with the 'u' flag.
  usingBungee: false


  # By default, StarGate uses a local SQLite database to store its data.
  #
  # If you are running a large server, we recommend using a remote database.
  # Note that such a database is required if you intend on building gates with the 'i' flag.
  useRemoteDatabase: false
```

Migrated:
```

# SG protects gate 𝑓𝑟𝑎𝑚𝑒 materials; should it also protect gate 𝑎𝑝𝑒𝑟𝑡𝑢𝑟𝑒 (open/closed) materials?
# ex. in nether.gate, should nether_portal be protected?

# +----------------------------------------------------------------------------------------------+ #
# |                                       Aesthetic Tweaks                                       | #
# +----------------------------------------------------------------------------------------------+ #
language: en
bungee:

  # By default, SG will preface its remote database tables with `SG_`.
  # If this conflicts with another plugin, you can change that prefix here.
  usingBungee: false

  # An internal value used by the plugin to determine how old your config is.
  # Please do not change this.
  useRemoteDatabase: false
```

For some reason, it's just this section that's problematic. Everything else is fine.
