### ISSUE TITLE
`Knarvik 0.9.3.7` Migration Parity & Handling [TMS]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#162]
> Discovered in `[TMS 222179]`
1. When the SG migrator encounters configuration strings that it does not understand, it appends them to the end of the migrated configuration file with no context.
  - A comment may be helpful for understanding what happened.
2. SG's migrator does not fully support the most recent version of Knarvik's confiruation. Most notably, it does not transfer the exitVelocity value.

# Environment
**Plugin Version**: `ALPHA-1.0.0.4` (Migrating Knarvik 0.9.3.7, Test Environment unit `2-Paper-Offline-MigKnar-Modern-SQL`)
**Server Version**: `git-Paper-350` (MC: 1.18.2) Implementing API Version `1.18.2-R0.1-SNAPSHOT`

# Description.
## Input
See [here](https://github.com/Pheotis/Stargate-Test-Environment/blob/main/2-Paper-Offline-MigKnar-Modern-SQL/plugins/Stargate/config.yml)

## Output Mismatch:
```yaml
configVersion: 7
gates:
  exitVelocity: 0.1
  cosmetic:
    perSignColors:
    - ACACIA:default,default
    - BIRCH:default,default
    - CRIMSON:inverted,inverted
    - DARK_OAK:inverted,inverted
    - JUNGLE:default,default
    - OAK:default,default
    - SPRUCE:inverted,inverted
    - WARPED:inverted,inverted
  functionality:
    enableCraftBookRemoveOnEjectFix: false
advanced:
  waitForPlayerAfterTeleportDelay: 6
```
