### ISSUE TITLE
Material lists can not include multiple tags.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#294]
Report submitted through discord, not yet fully verified.

> ***Sadbot#8138 wrote on May 23, 2023:*** *(paraphrased)*
> According to the wiki, "valid materials and/or tags can be stringed together through the use of commas" are supported.
> From the looks of it, these stringed lists can only include a maximum of one tag.
> 
> ✔️  `SMOOTH_QUARTZ`, `COBBLESTONE`, `#WOOL`
> ❌ `SMOOTH_QUARTZ`, `#WOOL`, `#BEACON_BASE_BLOCKS`
> ✔️  `SMOOTH_QUARTZ`, `#BEACON_BASE_BLOCKS`
> ❌ `#WOOL`, `#BEACON_BASE_BLOCKS`

```yaml
OS: Windows 10 Home
Server: paper-1.19.4-533
Stargate: Stargate-0.11.5.3
Java: ? Probably 17.
```
