### ISSUE TITLE
Name length filter trigers outside of Stargate creation.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#307]
### Bug Description

Any sign that is too long, regardless of whether it is being used to make a stargate, will produce the Name too short or too long! warning.

### Reproduction Steps

Make a sign with too much text.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/2e0d7ce5-d51c-48d9-8fe6-451cbdffb5bb)

### Desired Behaviour

The sign should behave like any normal sign.

### Observed Behaviour

The sign behaves normally, but produces this error.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/170e7168-c2a9-4d1c-9be1-0b86b3ab80fc)

### Trace Logs

```yaml
BukkitInstance: git-Paper-364 (MC: 1.20.4)
Stargate version: 1.0.0.14-ALPHA
JavaVersion: 17.0.9
OperatingSystem: Windows 11
```
